const fs = require('fs/promises');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/**
 * Gives Android notifications a large icon.
 *
 * ## Why this exists
 *
 * `expo-notifications` reads two manifest entries when it builds a
 * notification (`ExpoNotificationBuilder.kt`):
 *
 *   expo.modules.notifications.default_notification_icon   the small icon
 *   expo.modules.notifications.large_notification_icon     the large icon
 *
 * Its own config plugin writes the first and **not** the second — there is a
 * `TODO @vonovak add config for local notification large icon` in
 * `withNotificationsAndroid.js` saying as much. With the key absent the builder
 * calls `setLargeIcon(null)`, and Android falls back to drawing the launcher
 * icon in that slot.
 *
 * That fallback is why Haala notifications showed the stock Android robot for
 * as long as the app had no launcher icon, and why it stayed wrong through a
 * reinstall: nothing about the small icon, the payload or the icon cache was
 * ever involved.
 *
 * ## Why a plugin rather than dropping files in `android/`
 *
 * `apps/*∕android/` is gitignored and regenerated by `expo prebuild` on every
 * EAS build, so anything written there by hand is deleted before it compiles.
 * A config plugin runs *during* prebuild, which is the only durable place to
 * put this.
 *
 * ## The asset
 *
 * Unlike the small icon — which Android reduces to its alpha channel, so it
 * must be a white silhouette — a large icon is a full-colour bitmap. These are
 * the ember tile with the Now Dot mark, pre-rendered per density so the build
 * does no image processing.
 */

const META_DATA_LARGE_ICON = 'expo.modules.notifications.large_notification_icon';
const RESOURCE_NAME = 'notification_large_icon';

/** Density buckets, matching the ones `expo-notifications` itself writes to. */
const BUCKETS = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'];

/** Where the pre-rendered tiles live, relative to the app root. */
const SOURCE_DIR = path.join('assets', 'notification-large');

const withLargeIconAssets = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;

      for (const bucket of BUCKETS) {
        const from = path.join(projectRoot, SOURCE_DIR, `${bucket}.png`);
        /*
         * Fail loudly. A missing source silently produces a notification with
         * no large icon — which is the exact bug this plugin exists to fix, and
         * it would look identical to not having installed the plugin at all.
         */
        await fs.access(from).catch(() => {
          throw new Error(
            `withLargeNotificationIcon: ${SOURCE_DIR}/${bucket}.png is missing. ` +
              `All ${BUCKETS.length} density buckets must be present.`,
          );
        });

        const dir = path.join(platformProjectRoot, 'app', 'src', 'main', 'res', `drawable-${bucket}`);
        await fs.mkdir(dir, { recursive: true });
        await fs.copyFile(from, path.join(dir, `${RESOURCE_NAME}.png`));
      }

      return cfg;
    },
  ]);

const withLargeIconManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    // `resource` rather than `value`: the builder calls `metaData.getInt(...)`
    // and decodes it as a drawable id, so a string path would read as 0.
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      META_DATA_LARGE_ICON,
      `@drawable/${RESOURCE_NAME}`,
      'resource',
    );
    return cfg;
  });

module.exports = (config) => withLargeIconManifest(withLargeIconAssets(config));
